### PR TITLE
Migrate to React v18 lifecycle methods, update packages and NodeJS version

### PR DESCRIPTION
**Pull request by mhieta**
Updates:
- Migrate to React v18 lifecycle methods:
   - Move componentWillMount logic to constructor
   - Replace componentWillReceiveProps with static getDerivedStateFromProps
   - Add propsTypes to LoginScreen-component
- Remove unused open-package and code
- Update packages
- Use latest NodeJS v22 slim image as app base
- Use latest stable Nginx version

Refs HUL-15

### CODE REVIEW

**Comment by terovirtanen** [comment]
**SPORTS-MAINTENANCE-DASHBOARD branch is deployed to platta: https://pulkka-ulkoliikunta-pr34.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**SPORTS-MAINTENANCE-DASHBOARD branch is deployed to platta: https://pulkka-ulkoliikunta-pr34.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**SPORTS-MAINTENANCE-DASHBOARD branch is deployed to platta: https://pulkka-ulkoliikunta-pr34.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**SPORTS-MAINTENANCE-DASHBOARD branch is deployed to platta: https://pulkka-ulkoliikunta-pr34.dev.hel.ninja** :rocket::rocket::rocket:

**Review by japauliina — APPROVED** [review]
Nice work!

**Comment by terovirtanen** [comment]
**SPORTS-MAINTENANCE-DASHBOARD branch is deployed to platta: https://pulkka-ulkoliikunta-pr34.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
